name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Vérifie le code du repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Se connecte à Docker Hub (ou autre registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construit l'image Docker
    - name: Build Docker Image
      run: |
        docker build -t vincentdub/service-users:latest -f Dockerfile .

    # Pousse l'image dans le repository centralisé
    - name: Push Docker Image
      run: |
        docker push vincentdub/service-users:latest
